"""Report exporters: JSON (canonical), Markdown, PDF, and interactive HTML."""
from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Optional

from ...core.schema import ScanReport

_SEVERITY_COLORS = {
    "critical": "#7b1fa2",
    "high": "#c62828",
    "medium": "#ef6c00",
    "low": "#f9a825",
    "info": "#546e7a",
}


# ---------------- JSON ----------------
def to_json(report: ScanReport, indent: int = 2) -> str:
    return report.model_dump_json(indent=indent)


def write_json(report: ScanReport, out_dir: Path) -> Path:
    path = out_dir / f"report-{report.id}.json"
    path.write_text(to_json(report), encoding="utf-8")
    return path


# ---------------- Markdown ----------------
def to_markdown(report: ScanReport) -> str:
    lines = [f"# Security Audit Report — {report.target.input}", ""]
    lines.append(f"- **Report ID:** {report.id}")
    lines.append(f"- **Resolved IPs:** {', '.join(report.target.resolved_ips) or 'n/a'}")
    lines.append(f"- **Scope authorized:** {report.scope_authorized}")
    lines.append(f"- **Started:** {report.started_at}")
    lines.append(f"- **Finished:** {report.finished_at}")
    lines.append("")

    counts = report.severity_counts()
    lines.append("## Summary")
    lines.append(
        "| Critical | High | Medium | Low | Info |\n|---|---|---|---|---|\n"
        f"| {counts['critical']} | {counts['high']} | {counts['medium']} | "
        f"{counts['low']} | {counts['info']} |"
    )
    lines.append("")

    lines.append("## Findings")
    findings = report.findings_by_severity()
    if not findings:
        lines.append("_No findings._")
    for f in findings:
        lines.append(f"### [{f.severity.value.upper()}] {f.title}")
        lines.append(f"- **Module:** {f.module}")
        if f.description:
            lines.append(f"- **Detail:** {f.description}")
        if f.evidence:
            lines.append(f"- **Evidence:** `{f.evidence}`")
        if f.references:
            lines.append(f"- **References:** {', '.join(f.references)}")
        lines.append("")

    if report.remediation:
        lines.append("## Remediation Plan")
        lines.append(f"_{report.remediation.summary}_ "
                     f"(generated by: {report.remediation.generated_by})")
        lines.append("")
        for step in report.remediation.prioritized_steps:
            lines.append(f"{step.priority}. **[{step.severity.value.upper()}] "
                         f"{step.title}** — {step.action}")
        lines.append("")

    return "\n".join(lines)


def write_markdown(report: ScanReport, out_dir: Path) -> Path:
    path = out_dir / f"report-{report.id}.md"
    path.write_text(to_markdown(report), encoding="utf-8")
    return path


# ---------------- HTML (interactive web view) ----------------
def to_html(report: ScanReport) -> str:
    counts = report.severity_counts()

    def esc(v) -> str:
        return html.escape(str(v)) if v is not None else ""

    finding_rows = []
    for f in report.findings_by_severity():
        color = _SEVERITY_COLORS.get(f.severity.value, "#546e7a")
        finding_rows.append(
            f"<tr><td><span class='sev' style='background:{color}'>"
            f"{esc(f.severity.value.upper())}</span></td>"
            f"<td>{esc(f.module)}</td><td><strong>{esc(f.title)}</strong><br>"
            f"<small>{esc(f.description)}</small></td>"
            f"<td><code>{esc(f.evidence or '')}</code></td></tr>"
        )

    rem_rows = []
    if report.remediation:
        for s in report.remediation.prioritized_steps:
            color = _SEVERITY_COLORS.get(s.severity.value, "#546e7a")
            rem_rows.append(
                f"<li><span class='sev' style='background:{color}'>"
                f"{esc(s.severity.value.upper())}</span> "
                f"<strong>{esc(s.title)}</strong> — {esc(s.action)}</li>"
            )

    summary = esc(report.remediation.summary) if report.remediation else ""
    generated_by = esc(report.remediation.generated_by) if report.remediation else "n/a"

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Audit Report {esc(report.id)}</title>
<style>
 body{{font-family:system-ui,Arial,sans-serif;margin:2rem;color:#1a1a1a;background:#fafafa}}
 h1{{margin-bottom:0}} .meta{{color:#555;font-size:.9rem}}
 table{{border-collapse:collapse;width:100%;margin:1rem 0;background:#fff}}
 th,td{{border:1px solid #e0e0e0;padding:.5rem;text-align:left;vertical-align:top}}
 th{{background:#f0f0f0}}
 .sev{{color:#fff;padding:.1rem .5rem;border-radius:.4rem;font-size:.75rem;font-weight:600}}
 .cards{{display:flex;gap:.5rem;flex-wrap:wrap}}
 .card{{padding:.6rem 1rem;border-radius:.5rem;color:#fff;font-weight:600}}
 code{{background:#f3f3f3;padding:.1rem .3rem;border-radius:.3rem}}
</style></head><body>
<h1>Security Audit Report</h1>
<div class="meta">Target: <strong>{esc(report.target.input)}</strong> &middot;
 IPs: {esc(', '.join(report.target.resolved_ips) or 'n/a')} &middot;
 Report ID: {esc(report.id)} &middot; Authorized: {esc(report.scope_authorized)}</div>
<div class="cards" style="margin-top:1rem">
 <div class="card" style="background:{_SEVERITY_COLORS['critical']}">Critical {counts['critical']}</div>
 <div class="card" style="background:{_SEVERITY_COLORS['high']}">High {counts['high']}</div>
 <div class="card" style="background:{_SEVERITY_COLORS['medium']}">Medium {counts['medium']}</div>
 <div class="card" style="background:{_SEVERITY_COLORS['low']}">Low {counts['low']}</div>
 <div class="card" style="background:{_SEVERITY_COLORS['info']}">Info {counts['info']}</div>
</div>
<h2>Findings</h2>
<table><thead><tr><th>Severity</th><th>Module</th><th>Finding</th><th>Evidence</th></tr></thead>
<tbody>{''.join(finding_rows) or '<tr><td colspan=4>No findings.</td></tr>'}</tbody></table>
<h2>Remediation Plan <small>({generated_by})</small></h2>
<p>{summary}</p>
<ol>{''.join(rem_rows) or '<li>No remediation steps.</li>'}</ol>
</body></html>"""


def write_html(report: ScanReport, out_dir: Path) -> Path:
    path = out_dir / f"report-{report.id}.html"
    path.write_text(to_html(report), encoding="utf-8")
    return path


# ---------------- PDF ----------------
def write_pdf(report: ScanReport, out_dir: Path) -> Optional[Path]:
    """Render a PDF with reportlab. Returns None if reportlab is unavailable."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError:
        return None

    path = out_dir / f"report-{report.id}.pdf"
    styles = getSampleStyleSheet()
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=8, leading=10)
    doc = SimpleDocTemplate(str(path), pagesize=letter, title=f"Audit Report {report.id}")
    story = [
        Paragraph(f"Security Audit Report — {report.target.input}", styles["Title"]),
        Paragraph(
            f"Report ID: {report.id} &nbsp; IPs: {', '.join(report.target.resolved_ips) or 'n/a'} "
            f"&nbsp; Authorized: {report.scope_authorized}",
            styles["Normal"],
        ),
        Spacer(1, 12),
        Paragraph("Findings", styles["Heading2"]),
    ]

    data = [["Severity", "Module", "Finding", "Evidence"]]
    for f in report.findings_by_severity():
        data.append([
            f.severity.value.upper(),
            f.module,
            Paragraph(f"<b>{html.escape(f.title)}</b><br/>{html.escape(f.description)}", small),
            Paragraph(html.escape(f.evidence or ""), small),
        ])
    if len(data) == 1:
        data.append(["", "", "No findings.", ""])
    table = Table(data, colWidths=[55, 60, 250, 130])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#333333")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1, 12))

    if report.remediation:
        story.append(Paragraph("Remediation Plan", styles["Heading2"]))
        story.append(Paragraph(html.escape(report.remediation.summary), styles["Normal"]))
        story.append(Spacer(1, 6))
        for s in report.remediation.prioritized_steps:
            story.append(Paragraph(
                f"{s.priority}. [{s.severity.value.upper()}] "
                f"<b>{html.escape(s.title)}</b> — {html.escape(s.action)}", small))

    doc.build(story)
    return path


def export_all(report: ScanReport, out_dir: Path) -> dict:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    result = {
        "json": str(write_json(report, out_dir)),
        "markdown": str(write_markdown(report, out_dir)),
        "html": str(write_html(report, out_dir)),
    }
    pdf = write_pdf(report, out_dir)
    result["pdf"] = str(pdf) if pdf else None
    return result
